✨ Check Node Name while doing InstanceExist
hivelocity/hivelocity-cloud-controller-manager pull request #22
Opened 2023-10-16 11:08 UTC by aniruddha2000

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #18 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squash commits
- [ ] include documentation
- [ ] add unit tests

2023-10-16 14:05 UTC, janiskemper requested changes

2023-10-16 14:05 UTC, janiskemper commented on client/client.go
> +	ListDevice(context.Context) ([]hv.BareMetalDevice, error)
ListDevices

2023-10-16 14:05 UTC, janiskemper commented on hivelocity/instances_v2.go
> +				"[InstanceExists] getHivelocityDeviceIDFromNode() failed. node %q: %w",
wrong function InstanceExists

2023-10-16 14:05 UTC, janiskemper commented on hivelocity/instances_v2.go
> +			if err != nil {
if there is no such tag, you don't want to throw an error but return nil, because then the device does not belong to this cluster anymore

2023-10-16 14:05 UTC, janiskemper commented on hivelocity/instances_v2.go
> +		return nil, client.ErrNoSuchDevice
here you return an error, and on top you return nil, nil.. From what I see how you use it in InstanceExists I don't think you should return an error here...

2023-10-16 14:05 UTC, janiskemper commented on hivelocity/instances_v2.go
> +
what if device is nil? -> should be an error I guess. re-check in cloud-provider interface for more infos and Hetzner CCM for another resource

2023-10-16 14:05 UTC, janiskemper commented on hivelocity/instances_v2.go
> +	device, err := i2.lookUpDevice(ctx, node)
handle device == nil

2023-10-17 06:37 UTC, janiskemper requested changes

2023-10-17 06:37 UTC, janiskemper commented on client/client.go
> +// ListDevices list all the BareMetal Devices via Hivelocity API.
ListDevices lists all devices via Hivelocity API.

2023-10-17 06:37 UTC, janiskemper commented on client/client.go
> +	var result struct {
you never use the result

2023-10-17 06:37 UTC, janiskemper commented on hivelocity/instances_v2.go
> +			"[InstanceExists] ListDevice() failed. node %q: %w",
ListDevices

2023-10-17 06:37 UTC, janiskemper commented on hivelocity/instances_v2.go
> +		if err != nil {
you should skip the device, not return if the device does not fit

2023-10-17 09:19 UTC, janiskemper approved these changes
I think rebasing will solve your linting problems. I guess we removed the linter in the other PR

2023-10-17 10:06 UTC, aniruddha2000 commented
the last commit on main was month ago, are you sure rebase will solve it?

2023-10-17 10:44 UTC, janiskemper commented
merged the other PR. now you can rebase

2023-10-17 13:59 UTC, janiskemper approved these changes

2023-10-18 06:26 UTC, merged